# Generated by Django 2.1.7 on 2019-09-03 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adocao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItensCarrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adocao.Produto')),
            ],
        ),
    ]
