# Generated by Django 2.1.7 on 2019-11-08 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0005_auto_20191004_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornecedor',
            old_name='telefone',
            new_name='telefone_fornecedor',
        ),
    ]
