# Generated by Django 2.1.7 on 2019-11-08 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0006_auto_20191108_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornecedor',
            old_name='telefone_fornecedor',
            new_name='telefone',
        ),
    ]
