# Generated by Django 2.1.7 on 2019-11-29 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0010_auto_20191112_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtde', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_chegada', models.DateField()),
                ('observacao', models.TextField(blank=True, help_text='qual quer informação adicional do produto', null=True, verbose_name='Observação')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adocao.Produto')),
            ],
        ),
        migrations.AlterField(
            model_name='venda',
            name='desconto',
            field=models.CharField(blank=True, choices=[('00%', 'Venda sem desconto'), ('05%', '05%'), ('10%', '10%'), ('15%', '15%'), ('20%', '20%'), ('25%', '25%'), ('35%', '35%'), ('40%', '40%'), ('45%', '45%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('75%', '75%')], max_length=4, null=True),
        ),
    ]
